version: "3"
services:

  plex-rclone:
    container_name: plex-test
    environment:
      - RCLONE_VERSION=latest
      - RCLONE_BETA=yes
      - PLEX_UID=101
      - PLEX_GID=101
      - TAUTULLI_UID=102
      - TAUTULLI_GID=102
    build:
      context: ./build
    networks:
      main_lan:
        ipv4_address: 192.168.10.114
    image: plex
    volumes:
      - ${HOME}/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf
      - ${HOME}/plex_data:/config
    command: sleep infinity
    privileged: true
    security_opt:
      - seccomp:unconfined
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN

networks:
  main_lan:
    external:
      name: pub_net

