version: "3.8"
services:
  plex:
    build:
      context: build
    container_name: plex-docker
    hostname: plex-docker
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - "apparmor:unconfined"
    ports:
      - 32400:32400/tcp
    volumes:
      - ${PWD}/metadata:/config
# Rclone config file already setup
      - ${PWD}/rclone:/root/rclone
# Directory for rclone cache
      - ${PWD}/tmp:/tmp
    environment:
      - TZ=Europe/London
#      - PLEX_UID=112
#      - PLEX_GID=117
# Needs the docker host ip in here (along with port if different)
      - ADVERTISE_IP=http://192.168.10.57:32400/
# Needs the subnet in here
      - ALLOWED_NETWORKS=192.168.10.0/24
# Get plex claim token from https://www.plex.tv/claim/
      - PLEX_CLAIM=claim-xxxxxxxxxxxxxxxxxxxx
# Rclone config as set in the volumes above
      - RCLONE_CONFIG=/root/rclone/rclone.conf
# Rclone remote path
      - RCLONE_REMOTE=remote:/path
# Rclone local mount point (will create directory if necessary)
      - RCLONE_MOUNT=/mnt
# Other rclone environment variables can be added here
# allow other is hardcoded in script, so not strictly necessary here
#      - RCLONE_ALLOW_OTHER=true
      - RCLONE_READ_ONLY=true
      - RCLONE_BUFFER_SIZE=50M
      - RCLONE_FAST_LIST=true
      - RCLONE_VFS_CACHE_MAX_AGE=3h 
      - RCLONE_VFS_CACHE_MODE=full
      - RCLONE_VFS_CACHE_POLL_INTERVAL=1m
      - RCLONE_VFS_CACHE_MAX_SIZE=10g
      - RCLONE_CACHE_DIR=/tmp
      - RCLONE_VERBOSE=1
